// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// BigDerivMat
void BigDerivMat(SEXP pinBigX, SEXP pInSigma, SEXP pInKernel, SEXP pInCoeffs, SEXP pInVCovMatC, SEXP pInBigXSD, SEXP pOutDerivatives, SEXP pOutVarAvgDerivatives);
RcppExport SEXP bigKRLS_BigDerivMat(SEXP pinBigXSEXP, SEXP pInSigmaSEXP, SEXP pInKernelSEXP, SEXP pInCoeffsSEXP, SEXP pInVCovMatCSEXP, SEXP pInBigXSDSEXP, SEXP pOutDerivativesSEXP, SEXP pOutVarAvgDerivativesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type pinBigX(pinBigXSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pInSigma(pInSigmaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pInKernel(pInKernelSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pInCoeffs(pInCoeffsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pInVCovMatC(pInVCovMatCSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pInBigXSD(pInBigXSDSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pOutDerivatives(pOutDerivativesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pOutVarAvgDerivatives(pOutVarAvgDerivativesSEXP);
    BigDerivMat(pinBigX, pInSigma, pInKernel, pInCoeffs, pInVCovMatC, pInBigXSD, pOutDerivatives, pOutVarAvgDerivatives);
    return R_NilValue;
END_RCPP
}
// BigCrossProd
void BigCrossProd(SEXP pInBigMatA, SEXP pInBigMatB, SEXP pOutBigMat);
RcppExport SEXP bigKRLS_BigCrossProd(SEXP pInBigMatASEXP, SEXP pInBigMatBSEXP, SEXP pOutBigMatSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type pInBigMatA(pInBigMatASEXP);
    Rcpp::traits::input_parameter< SEXP >::type pInBigMatB(pInBigMatBSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pOutBigMat(pOutBigMatSEXP);
    BigCrossProd(pInBigMatA, pInBigMatB, pOutBigMat);
    return R_NilValue;
END_RCPP
}
// BigEigen
void BigEigen(SEXP pInBigMat, SEXP pInEigTrunc, SEXP pValBigMat, SEXP pVecBigMat);
RcppExport SEXP bigKRLS_BigEigen(SEXP pInBigMatSEXP, SEXP pInEigTruncSEXP, SEXP pValBigMatSEXP, SEXP pVecBigMatSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type pInBigMat(pInBigMatSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pInEigTrunc(pInEigTruncSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pValBigMat(pValBigMatSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pVecBigMat(pVecBigMatSEXP);
    BigEigen(pInBigMat, pInEigTrunc, pValBigMat, pVecBigMat);
    return R_NilValue;
END_RCPP
}
// BigElementwise
void BigElementwise(SEXP pInMatX, SEXP pInMatY, SEXP poutBigMat);
RcppExport SEXP bigKRLS_BigElementwise(SEXP pInMatXSEXP, SEXP pInMatYSEXP, SEXP poutBigMatSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type pInMatX(pInMatXSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pInMatY(pInMatYSEXP);
    Rcpp::traits::input_parameter< SEXP >::type poutBigMat(poutBigMatSEXP);
    BigElementwise(pInMatX, pInMatY, poutBigMat);
    return R_NilValue;
END_RCPP
}
// BigGaussKernel
void BigGaussKernel(SEXP pInBigMat, SEXP pOutBigMat, SEXP pSigma);
RcppExport SEXP bigKRLS_BigGaussKernel(SEXP pInBigMatSEXP, SEXP pOutBigMatSEXP, SEXP pSigmaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type pInBigMat(pInBigMatSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pOutBigMat(pOutBigMatSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pSigma(pSigmaSEXP);
    BigGaussKernel(pInBigMat, pOutBigMat, pSigma);
    return R_NilValue;
END_RCPP
}
// BigMultDiag
void BigMultDiag(SEXP pToMult, SEXP pVecMat, SEXP pOutMat);
RcppExport SEXP bigKRLS_BigMultDiag(SEXP pToMultSEXP, SEXP pVecMatSEXP, SEXP pOutMatSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type pToMult(pToMultSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pVecMat(pVecMatSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pOutMat(pOutMatSEXP);
    BigMultDiag(pToMult, pVecMat, pOutMat);
    return R_NilValue;
END_RCPP
}
// BigTCrossProd
void BigTCrossProd(SEXP pInBigMatA, SEXP pInBigMatB, SEXP pOutBigMat);
RcppExport SEXP bigKRLS_BigTCrossProd(SEXP pInBigMatASEXP, SEXP pInBigMatBSEXP, SEXP pOutBigMatSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type pInBigMatA(pInBigMatASEXP);
    Rcpp::traits::input_parameter< SEXP >::type pInBigMatB(pInBigMatBSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pOutBigMat(pOutBigMatSEXP);
    BigTCrossProd(pInBigMatA, pInBigMatB, pOutBigMat);
    return R_NilValue;
END_RCPP
}
// BigTempKernel
void BigTempKernel(SEXP pInBigMat, SEXP pOutBigMat, SEXP pSigma);
RcppExport SEXP bigKRLS_BigTempKernel(SEXP pInBigMatSEXP, SEXP pOutBigMatSEXP, SEXP pSigmaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type pInBigMat(pInBigMatSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pOutBigMat(pOutBigMatSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pSigma(pSigmaSEXP);
    BigTempKernel(pInBigMat, pOutBigMat, pSigma);
    return R_NilValue;
END_RCPP
}
