# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BigDerivMat <- function(pX, pK, pVCovMatC, pDerivatives, pVarAvgDerivatives, Xsd, coeffs, sigma) {
    invisible(.Call(`_bigKRLS_BigDerivMat`, pX, pK, pVCovMatC, pDerivatives, pVarAvgDerivatives, Xsd, coeffs, sigma))
}

BigCrossProd <- function(pA, pB, pOut) {
    invisible(.Call(`_bigKRLS_BigCrossProd`, pA, pB, pOut))
}

BigTCrossProd <- function(pA, pB, pOut) {
    invisible(.Call(`_bigKRLS_BigTCrossProd`, pA, pB, pOut))
}

BigEigen <- function(pA, Eigtrunc, pValBigMat, pVecBigMat) {
    invisible(.Call(`_bigKRLS_BigEigen`, pA, Eigtrunc, pValBigMat, pVecBigMat))
}

BigGaussKernel <- function(pA, pOut, sigma) {
    invisible(.Call(`_bigKRLS_BigGaussKernel`, pA, pOut, sigma))
}

BigMultDiag <- function(pA, diag, pOut) {
    invisible(.Call(`_bigKRLS_BigMultDiag`, pA, diag, pOut))
}

BigNeffective <- function(pX) {
    .Call(`_bigKRLS_BigNeffective`, pX)
}

BigSolveForc <- function(pEigenvectors, Eigenvalues, y, lambda) {
    .Call(`_bigKRLS_BigSolveForc`, pEigenvectors, Eigenvalues, y, lambda)
}

BigTempKernel <- function(pA, pB, pOut, sigma) {
    invisible(.Call(`_bigKRLS_BigTempKernel`, pA, pB, pOut, sigma))
}

