# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BigCrossProd <- function(pInBigMatA, pInBigMatB, pOutBigMat) {
    invisible(.Call('bigKRLS_BigCrossProd', PACKAGE = 'bigKRLS', pInBigMatA, pInBigMatB, pOutBigMat))
}

BigEigen <- function(pInBigMat, pValBigMat, pVecBigMat) {
    invisible(.Call('bigKRLS_BigEigen', PACKAGE = 'bigKRLS', pInBigMat, pValBigMat, pVecBigMat))
}

BigElementwise <- function(pInMatX, pInMatY, poutBigMat) {
    invisible(.Call('bigKRLS_BigElementwise', PACKAGE = 'bigKRLS', pInMatX, pInMatY, poutBigMat))
}

BigGaussKernel <- function(pInBigMat, pOutBigMat, pSigma) {
    invisible(.Call('bigKRLS_BigGaussKernel', PACKAGE = 'bigKRLS', pInBigMat, pOutBigMat, pSigma))
}

BigMultDiag <- function(pToMult, pVecMat, pOutMat) {
    invisible(.Call('bigKRLS_BigMultDiag', PACKAGE = 'bigKRLS', pToMult, pVecMat, pOutMat))
}

BigTCrossProd <- function(pInBigMatA, pInBigMatB, pOutBigMat) {
    invisible(.Call('bigKRLS_BigTCrossProd', PACKAGE = 'bigKRLS', pInBigMatA, pInBigMatB, pOutBigMat))
}

BigTempKernel <- function(pInBigMat, pOutBigMat, pSigma) {
    invisible(.Call('bigKRLS_BigTempKernel', PACKAGE = 'bigKRLS', pInBigMat, pOutBigMat, pSigma))
}

