# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BigDerivMat <- function(pinBigX, pInSigma, pInKernel, pInCoeffs, pInVCovMatC, pInBigXSD, pOutDerivatives, pOutVarAvgDerivatives) {
    invisible(.Call('bigKRLS_BigDerivMat', PACKAGE = 'bigKRLS', pinBigX, pInSigma, pInKernel, pInCoeffs, pInVCovMatC, pInBigXSD, pOutDerivatives, pOutVarAvgDerivatives))
}

BigCrossProd <- function(pInBigMatA, pInBigMatB, pOutBigMat) {
    invisible(.Call('bigKRLS_BigCrossProd', PACKAGE = 'bigKRLS', pInBigMatA, pInBigMatB, pOutBigMat))
}

BigEigen <- function(pInBigMat, pInEigTrunc, pValBigMat, pVecBigMat) {
    invisible(.Call('bigKRLS_BigEigen', PACKAGE = 'bigKRLS', pInBigMat, pInEigTrunc, pValBigMat, pVecBigMat))
}

BigElementwise <- function(pInMatX, pInMatY, poutBigMat) {
    invisible(.Call('bigKRLS_BigElementwise', PACKAGE = 'bigKRLS', pInMatX, pInMatY, poutBigMat))
}

BigGaussKernel <- function(pInBigMat, pOutBigMat, pSigma) {
    invisible(.Call('bigKRLS_BigGaussKernel', PACKAGE = 'bigKRLS', pInBigMat, pOutBigMat, pSigma))
}

BigMultDiag <- function(pToMult, pVecMat, pOutMat) {
    invisible(.Call('bigKRLS_BigMultDiag', PACKAGE = 'bigKRLS', pToMult, pVecMat, pOutMat))
}

BigTCrossProd <- function(pInBigMatA, pInBigMatB, pOutBigMat) {
    invisible(.Call('bigKRLS_BigTCrossProd', PACKAGE = 'bigKRLS', pInBigMatA, pInBigMatB, pOutBigMat))
}

BigTempKernel <- function(pInBigMatNew, pInBigMatOld, pOutBigMat, pSigma) {
    invisible(.Call('bigKRLS_BigTempKernel', PACKAGE = 'bigKRLS', pInBigMatNew, pInBigMatOld, pOutBigMat, pSigma))
}

